spring:
  application:
    name: fantasy-football-web-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    hikari:
      max-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true