spring:
  datasource:
    url: jdbc:postgresql://cloud-cockroachdb-public.cockroach.svc.cluster.local:26257/fantasy_football
    username: root
    hikari:
      schema: dev
      data-source-properties:
        sslmode: disable