spring:
  application:
    name: fantasy-football-web-api
management:
  tracing:
    enabled: false
  info:
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoint:
    env:
      show-values:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health,info,env,beans,metrics"
  otlp:
    metrics:
      export:
        enabled: false