[versions]
gradleReleasePluginVersion = "3.1.0"
fantasyFootballModelVersion = "2.0.5"
lombokPluginVersion = "8.13.1"
reactorBlockHoundVersion = "1.0.13.RELEASE"
openRewritePluginVersion = "7.6.2"
graalvmGradlePluginVersion = "0.10.6"
springBootPluginVersion = "3.5.0"

[libraries]
fantasyFootballModel = { group = "com.fantasy.football", name = "fantasy-football-model", version.ref = "fantasyFootballModelVersion" }
reactorBlockhound = { group = "io.projectreactor.tools", name = "blockhound", version.ref = "reactorBlockHoundVersion" }

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "springBootPluginVersion" }
gradleReleaePlugin = { id = "net.researchgate.release", version.ref = "gradleReleasePluginVersion" }
lombokPlugin = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }
openRewritePlugin = { id = "org.openrewrite.rewrite", version.ref = "openRewritePluginVersion" }
graalvmGradlePlugin = { id = "org.graalvm.buildtools.native", version.ref = "graalvmGradlePluginVersion" }