-- league team table
CREATE TABLE LEAGUE_TEAM (
    PULSE_ID INTEGER,
    SHRT_NAME VARCHAR(3),
    STRGTH INTEGER,
    STRGTH_ATT_AWAY INTEGER,
    STRGTH_ATT_HOME INTEGER,
    STRGTH_DEF_AWAY INTEGER,
    STRGTH_DEF_HOME INTEGER,
    STRGTH_OVR_AWAY INTEGER,
    STRGTH_OVR_HOME INTEGER,
    UN_AVLBL BOOLEAN,
    CODE INTEGER NOT NULL UNIQUE,
    DRAW INTEGER NOT NULL,
    FORM FLOAT(24) NOT NULL,
    LOSS INTEGER NOT NULL,
    PLAYED INTEGER NOT NULL,
    POINTS INTEGER NOT NULL,
    POSITION INTEGER NOT NULL,
    WIN INTEGER NOT NULL,
    VERSIONNUMBER BIGINT NOT NULL,
    TEAM_DIV VARCHAR(10),
    RECORDID UUID NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (CODE, RECORDID, NAME),
    UNIQUE (SHRT_NAME)
);
-- league team audit table
CREATE TABLE LEAGUE_TEAM_AUD (
    PULSE_ID INTEGER,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    SHRT_NAME VARCHAR(3),
    STRGTH INTEGER,
    STRGTH_ATT_AWAY INTEGER,
    STRGTH_ATT_HOME INTEGER,
    STRGTH_DEF_AWAY INTEGER,
    STRGTH_DEF_HOME INTEGER,
    STRGTH_OVR_AWAY INTEGER,
    STRGTH_OVR_HOME INTEGER,
    UN_AVLBL BOOLEAN,
    CODE INTEGER NOT NULL,
    DRAW INTEGER,
    FORM FLOAT(24),
    LOSS INTEGER,
    PLAYED INTEGER,
    POINTS INTEGER,
    POSITION INTEGER,
    WIN INTEGER,
    TEAM_DIV VARCHAR(10),
    RECORDID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (REV, CODE, RECORDID, NAME)
);

CREATE TABLE PLYR_BSC_INFO (
    PLYR_STS CHAR(1),
    SQD_NO INTEGER,
    TEAM_CODE INTEGER NOT NULL,
    CODE BIGINT NOT NULL,
    VERSIONNUMBER BIGINT NOT NULL,
    WEB_NAME VARCHAR(15),
    PLYR_FANT_STCS_PK UUID NOT NULL UNIQUE,
    PLYR_GAME_STCS_PK UUID NOT NULL UNIQUE,
    PLYR_MISC_INFO_PK UUID NOT NULL UNIQUE,
    TEAM_UUID UUID NOT NULL,
    RECORDID UUID NOT NULL,
    FRST_NAME VARCHAR(30) NOT NULL,
    SECD_NAME VARCHAR(30) NOT NULL,
    TEAM_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (CODE, RECORDID, FRST_NAME, SECD_NAME)
);

CREATE TABLE PLYR_BSC_INFO_AUD (
    PLYR_STS CHAR(1),
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    SQD_NO INTEGER,
    TEAM_CODE INTEGER,
    CODE BIGINT NOT NULL,
    WEB_NAME VARCHAR(15),
    PLYR_FANT_STCS_PK UUID,
    PLYR_GAME_STCS_PK UUID,
    PLYR_MISC_INFO_PK UUID,
    TEAM_UUID UUID,
    RECORDID UUID NOT NULL,
    FRST_NAME VARCHAR(30) NOT NULL,
    SECD_NAME VARCHAR(30) NOT NULL,
    TEAM_NAME VARCHAR(30),
    PRIMARY KEY (REV, CODE, RECORDID, FRST_NAME, SECD_NAME)
);

CREATE TABLE PLYR_FANT_STCS (
    CHNC_OF_PLYNG_CURR_RD INTEGER,
    CHNC_OF_PLYNG_NXT_RD INTEGER,
    CURR_COST INTEGER,
    DREAM_TM_CT INTEGER,
    EVT_PNTS INTEGER,
    EXP_ASSTS FLOAT(24),
    EXP_ASSTS_90 FLOAT(24),
    EXP_GOALS FLOAT(24),
    EXP_GOALS_90 FLOAT(24),
    EXP_GOALS_CNCDED FLOAT(24),
    EXP_GOALS_CNCDED_90 FLOAT(24),
    EXP_GOAL_INVLMTS FLOAT(24),
    EXP_GOAL_INVLMTS_90 FLOAT(24),
    EXP_PNTS_CURR FLOAT(24),
    EXP_PNTS_NXT FLOAT(24),
    IS_IN_DREAM_TM BOOLEAN,
    PNTS_PER_GAME FLOAT(24),
    SEL_BY_PRCT FLOAT(24),
    TOTAL_PNTS INTEGER,
    VAL_FROM FLOAT(24),
    VAL_SEASN FLOAT(24),
    BONUS INTEGER,
    BPS INTEGER,
    FORM FLOAT(24),
    TRNFR_IN BIGINT,
    TRNFR_OUT BIGINT,
    VERSIONNUMBER BIGINT NOT NULL,
    RECORDID UUID NOT NULL,
    PRIMARY KEY (RECORDID)
);

CREATE TABLE PLYR_FANT_STCS_AUD (
    CHNC_OF_PLYNG_CURR_RD INTEGER,
    CHNC_OF_PLYNG_NXT_RD INTEGER,
    CURR_COST INTEGER,
    DREAM_TM_CT INTEGER,
    EVT_PNTS INTEGER,
    EXP_ASSTS FLOAT(24),
    EXP_ASSTS_90 FLOAT(24),
    EXP_GOALS FLOAT(24),
    EXP_GOALS_90 FLOAT(24),
    EXP_GOALS_CNCDED FLOAT(24),
    EXP_GOALS_CNCDED_90 FLOAT(24),
    EXP_GOAL_INVLMTS FLOAT(24),
    EXP_GOAL_INVLMTS_90 FLOAT(24),
    EXP_PNTS_CURR FLOAT(24),
    EXP_PNTS_NXT FLOAT(24),
    IS_IN_DREAM_TM BOOLEAN,
    PNTS_PER_GAME FLOAT(24),
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    SEL_BY_PRCT FLOAT(24),
    TOTAL_PNTS INTEGER,
    VAL_FROM FLOAT(24),
    VAL_SEASN FLOAT(24),
    BONUS INTEGER,
    BPS INTEGER,
    FORM FLOAT(24),
    TRNFR_IN BIGINT,
    TRNFR_OUT BIGINT,
    RECORDID UUID NOT NULL,
    PRIMARY KEY (REV, RECORDID)
);

CREATE TABLE PLYR_GAME_STCS (
    ASSTS INTEGER,
    CLEAN_SHTS INTEGER,
    CLEAN_SHTS_90 FLOAT(24),
    GOALS_CNCDED INTEGER,
    GOALS_CNCDED_90 FLOAT(24),
    GOALS_SCRD INTEGER,
    MINS INTEGER,
    OWN_GOALS INTEGER,
    PEN_MISSED INTEGER,
    PEN_SAVED INTEGER,
    RED_CARDS INTEGER,
    SAVES_90 FLOAT(24),
    STARTS_90 FLOAT(24),
    YELL_CARDS INTEGER,
    CREATIVITY FLOAT(24),
    INFLUENCE FLOAT(24),
    SAVES INTEGER,
    STARTS INTEGER,
    THREAT FLOAT(24),
    VERSIONNUMBER BIGINT NOT NULL,
    RECORDID UUID NOT NULL,
    PRIMARY KEY (RECORDID)
);

CREATE TABLE PLYR_GAME_STCS_AUD (
    ASSTS INTEGER,
    CLEAN_SHTS INTEGER,
    CLEAN_SHTS_90 FLOAT(24),
    GOALS_CNCDED INTEGER,
    GOALS_CNCDED_90 FLOAT(24),
    GOALS_SCRD INTEGER,
    MINS INTEGER,
    OWN_GOALS INTEGER,
    PEN_MISSED INTEGER,
    PEN_SAVED INTEGER,
    RED_CARDS INTEGER,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    SAVES_90 FLOAT(24),
    STARTS_90 FLOAT(24),
    YELL_CARDS INTEGER,
    CREATIVITY FLOAT(24),
    INFLUENCE FLOAT(24),
    SAVES INTEGER,
    STARTS INTEGER,
    THREAT FLOAT(24),
    RECORDID UUID NOT NULL,
    PRIMARY KEY (REV, RECORDID)
);

CREATE TABLE PLYR_MISC_INFO (
    CURR_COST_RANK INTEGER,
    CURR_COST_RANK_TYPE INTEGER,
    ICT_INDX FLOAT(24),
    PNTS_PER_GAME_RANK INTEGER,
    PNTS_PER_GAME_RANK_TYPE INTEGER,
    SEL_RANK INTEGER,
    SEL_RANK_TYPE INTEGER,
    CREATIVITYRANK INTEGER,
    CREATIVITYRANKTYPE INTEGER,
    FORMRANK INTEGER,
    FORMRANKTYPE INTEGER,
    ICTINDEXRANK INTEGER,
    ICTINDEXRANKTYPE INTEGER,
    INFLUENCERANK INTEGER,
    INFLUENCERANKTYPE INTEGER,
    THREATRANK INTEGER,
    THREATRANKTYPE INTEGER,
    NEWSADDED TIMESTAMP(6) WITH TIME ZONE,
    VERSIONNUMBER BIGINT NOT NULL,
    RECORDID UUID NOT NULL,
    CRNRS_AND_INDR_FK_ORDR VARCHAR(255),
    CRNRS_AND_INDR_FK_TX VARCHAR(255),
    DR_FK_ORDR VARCHAR(255),
    DR_FK_TX VARCHAR(255),
    PEN_ORDR VARCHAR(255),
    PEN_TX VARCHAR(255),
    NEWS VARCHAR(255),
    PRIMARY KEY (RECORDID)
);

CREATE TABLE PLYR_MISC_INFO_AUD (
    CURR_COST_RANK INTEGER,
    CURR_COST_RANK_TYPE INTEGER,
    ICT_INDX FLOAT(24),
    PNTS_PER_GAME_RANK INTEGER,
    PNTS_PER_GAME_RANK_TYPE INTEGER,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    SEL_RANK INTEGER,
    SEL_RANK_TYPE INTEGER,
    CREATIVITYRANK INTEGER,
    CREATIVITYRANKTYPE INTEGER,
    FORMRANK INTEGER,
    FORMRANKTYPE INTEGER,
    ICTINDEXRANK INTEGER,
    ICTINDEXRANKTYPE INTEGER,
    INFLUENCERANK INTEGER,
    INFLUENCERANKTYPE INTEGER,
    THREATRANK INTEGER,
    THREATRANKTYPE INTEGER,
    NEWSADDED TIMESTAMP(6) WITH TIME ZONE,
    RECORDID UUID NOT NULL,
    CRNRS_AND_INDR_FK_ORDR VARCHAR(255),
    CRNRS_AND_INDR_FK_TX VARCHAR(255),
    DR_FK_ORDR VARCHAR(255),
    DR_FK_TX VARCHAR(255),
    EN_ORDR VARCHAR(255),
    PEN_TX VARCHAR(255),
    NEWS VARCHAR(255),
    PRIMARY KEY (REV, RECORDID)
);

CREATE TABLE REVINFO (
    REV INTEGER NOT NULL,
    REVTSTMP BIGINT,
    APPLICATION_NAME VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    TRACE_ID VARCHAR(50),
    PRIMARY KEY (REV)
);

ALTER TABLE IF EXISTS LEAGUE_TEAM_AUD ADD CONSTRAINT FKF0CBTL31CY69FPAQWLONRLL2V FOREIGN KEY (REV) REFERENCES REVINFO;

ALTER TABLE IF EXISTS PLYR_BSC_INFO ADD CONSTRAINT FK9FQPD4W6IT01L9CS44UMECOJN FOREIGN KEY (PLYR_FANT_STCS_PK) REFERENCES PLYR_FANT_STCS;

ALTER TABLE IF EXISTS PLYR_BSC_INFO ADD CONSTRAINT FK3VI6ER8N6DGD9GCT1BC6TEFLC FOREIGN KEY (PLYR_GAME_STCS_PK) REFERENCES PLYR_GAME_STCS;

ALTER TABLE IF EXISTS PLYR_BSC_INFO ADD CONSTRAINT FKHWJLHJRMSCKBBARWX2H45K3QM FOREIGN KEY (PLYR_MISC_INFO_PK) REFERENCES PLYR_MISC_INFO;

ALTER TABLE IF EXISTS PLYR_BSC_INFO ADD CONSTRAINT FKHEN8GW9FYFC58UHKG1WBIB4DP FOREIGN KEY (TEAM_CODE, TEAM_UUID, TEAM_NAME) REFERENCES LEAGUE_TEAM;

ALTER TABLE IF EXISTS PLYR_BSC_INFO_AUD ADD CONSTRAINT FKQ2EGFDQFK1F2AV7MNTROFXDV5 FOREIGN KEY (REV) REFERENCES REVINFO;

ALTER TABLE IF EXISTS PLYR_FANT_STCS_AUD ADD CONSTRAINT FK5LFUNIOH73KXM48357JS376X6 FOREIGN KEY (REV) REFERENCES REVINFO;

ALTER TABLE IF EXISTS PLYR_GAME_STCS_AUD ADD CONSTRAINT FK8TC0P18MNF6BN5CB1SBUC2U9A FOREIGN KEY (REV) REFERENCES REVINFO;

ALTER TABLE IF EXISTS PLYR_MISC_INFO_AUD ADD CONSTRAINT FK74CEQC18ODM26Q29OPBO5CAFC FOREIGN KEY (REV) REFERENCES REVINFO;