ALTER TABLE LEAGUE_TEAM RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE LEAGUE_TEAM_AUD RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_BSC_INFO RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_BSC_INFO_AUD RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_FANT_STCS RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_FANT_STCS_AUD RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_GAME_STCS RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_GAME_STCS_AUD RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_MISC_INFO RENAME COLUMN RECORDID TO RECORD_ID;
ALTER TABLE PLYR_MISC_INFO_AUD RENAME COLUMN RECORDID TO RECORD_ID;

ALTER TABLE LEAGUE_TEAM RENAME COLUMN VERSIONNUMBER TO VERSION_NUMBER;
ALTER TABLE PLYR_BSC_INFO RENAME COLUMN VERSIONNUMBER TO VERSION_NUMBER;
ALTER TABLE PLYR_FANT_STCS RENAME COLUMN VERSIONNUMBER TO VERSION_NUMBER;
ALTER TABLE PLYR_GAME_STCS RENAME COLUMN VERSIONNUMBER TO VERSION_NUMBER;
ALTER TABLE PLYR_MISC_INFO RENAME COLUMN VERSIONNUMBER TO VERSION_NUMBER;

CREATE SEQUENCE REVINFO_SEQ START 1 INCREMENT 50