name: fantasy-football-web-api package publish
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout-action
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
          check-latest: true
      - name: Test with Maven
        if: github.ref_type == 'branch' && !(startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
        run: mvn --batch-mode --update-snapshots --show-version verify
      - name: Deploy with Maven
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
        run: mvn --batch-mode --show-version deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release with Maven
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        run: git config user.email "release-bot@example.com" && git config user.name "release-bot" && mvn --batch-mode release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Github packages Docker Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Configure Git for helm packaging
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run chart-releaser
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}