name: fantasy-football-web-api package publish
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout-action
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
          check-latest: true
      - name: Log in to the Github packages Docker Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with Maven
        if: github.ref_type == 'branch' && !(startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
        run: mvn -Pnative -Dspring-boot.aot.jvmArguments="-Dspring.main.cloud-platform=kubernetes -Dlogging.file.name=app.log" -Ddocker.publishRegistry.url=${{ env.REGISTRY }} -Ddocker.publishRegistry.username=${{ github.actor }} -Ddocker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }} -Dimage-repo=${{ env.REGISTRY }}/${{ github.repository_owner }} --batch-mode --update-snapshots --show-version package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release with Maven
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        run: git config user.email "release-bot@example.com" && git config user.name "release-bot" && mvn --batch-mode release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v5
        name: delete old versions
        with:
          package-name: 'com.fantasy.football.fantasy-football-web-api'
          package-type: 'maven'
          min-versions-to-keep: 2